server:
  port: 8888

spring:
  profiles:
    active: native  # Enable native profile
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config  # Look for configs in src/main/resources/config
            - file:./config      # Or look in external config directory